import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <header className='w-full h-[7vh] flex justify-around py-4 bg-gray-100'>
        <Link href={"/"}>Home</Link>
        <Link href={"/chat"}>Chat</Link>
        <Link href={"/sign-in"}>Sign in</Link>
        <Link href={"/sign-up"}>Sign up</Link>
        </header> 
        <main className='h-[93vh] bg-red-200'>

        {children}
        </main>
        </body>
    </html>
  )
}
